# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

inv_bijectionvector <- function(K, CL) {
    .Call(`_AHMQ_inv_bijectionvector`, K, CL)
}

twoToten <- function(x) {
    .Call(`_AHMQ_twoToten`, x)
}

ff <- function(a) {
    .Call(`_AHMQ_ff`, a)
}

pYi <- function(ETA_i, Y_i, ss, gs) {
    .Call(`_AHMQ_pYi`, ETA_i, Y_i, ss, gs)
}

Boolean <- function(A) {
    .Call(`_AHMQ_Boolean`, A)
}

Booleanvec <- function(A) {
    .Call(`_AHMQ_Booleanvec`, A)
}

Reachability <- function(StrucMat, K) {
    .Call(`_AHMQ_Reachability`, StrucMat, K)
}

ConnectMat <- function(R, K) {
    .Call(`_AHMQ_ConnectMat`, R, K)
}

Transitive <- function(G, K) {
    .Call(`_AHMQ_Transitive`, G, K)
}

mvrnormArma <- function(n, mu, sigma) {
    .Call(`_AHMQ_mvrnormArma`, n, mu, sigma)
}

AHM_sg <- function(Y, Q, ALPHAS, ss_old, as0, bs0, ag0, bg0) {
    .Call(`_AHMQ_AHM_sg`, Y, Q, ALPHAS, ss_old, as0, bs0, ag0, bg0)
}

maipow <- function(a, b) {
    .Call(`_AHMQ_maipow`, a, b)
}

vecpow_1_to_vec <- function(a, b) {
    .Call(`_AHMQ_vecpow_1_to_vec`, a, b)
}

vecpow <- function(a, b) {
    .Call(`_AHMQ_vecpow`, a, b)
}

add_path_sample1 <- function(R, G, K) {
    .Call(`_AHMQ_add_path_sample1`, R, G, K)
}

reduce_path_sample1 <- function(G, K) {
    .Call(`_AHMQ_reduce_path_sample1`, G, K)
}

Trans_10to2 <- function(K, CL) {
    .Call(`_AHMQ_Trans_10to2`, K, CL)
}

Trans_10to2_mat <- function(K, CL) {
    .Call(`_AHMQ_Trans_10to2_mat`, K, CL)
}

Accept_ratio_piprior <- function(y, s, g, pi0, delta0, alpha, alpha_new, Q, Q_new, G, G_new, alpha_possible_index, alpha_new_possible_index, alpha_possible_code, alpha_new_possible_code, alpha_possible, alpha_new_possible, pr_G, action, p1, p2) {
    .Call(`_AHMQ_Accept_ratio_piprior`, y, s, g, pi0, delta0, alpha, alpha_new, Q, Q_new, G, G_new, alpha_possible_index, alpha_new_possible_index, alpha_possible_code, alpha_new_possible_code, alpha_possible, alpha_new_possible, pr_G, action, p1, p2)
}

Trans_2to10 <- function(x, K) {
    .Call(`_AHMQ_Trans_2to10`, x, K)
}

Trans_2to10_mat <- function(x, K) {
    .Call(`_AHMQ_Trans_2to10_mat`, x, K)
}

Reduced_alpha1 <- function(alpha_all, R, K) {
    .Call(`_AHMQ_Reduced_alpha1`, alpha_all, R, K)
}

AHM_alpha <- function(y, s, g, Q, G, alpha_all, pi0, N, J, K, L) {
    .Call(`_AHMQ_AHM_alpha`, y, s, g, Q, G, alpha_all, pi0, N, J, K, L)
}

rDirichlet <- function(deltas) {
    .Call(`_AHMQ_rDirichlet`, deltas)
}

AHM_alpha_pi <- function(y, s, g, Q, G, alpha_all, pi0, delta0, N, J, K, L) {
    .Call(`_AHMQ_AHM_alpha_pi`, y, s, g, Q, G, alpha_all, pi0, delta0, N, J, K, L)
}

AHM_Q <- function(y, s, g, alpha, Q_all, Q, N, J, K, alpha_current_possible_index, eta, alpha_code) {
    .Call(`_AHMQ_AHM_Q`, y, s, g, alpha, Q_all, Q, N, J, K, alpha_current_possible_index, eta, alpha_code)
}

update_G <- function(y, s, g, alpha, alpha_all, Q, G, R, N, J, K, L, p1, p2, pi, delta0, G_new, prob_edge, action) {
    .Call(`_AHMQ_update_G`, y, s, g, alpha, alpha_all, Q, G, R, N, J, K, L, p1, p2, pi, delta0, G_new, prob_edge, action)
}

AHM_G <- function(y, s, g, alpha, alpha_all, Q, G, R, N, J, K, L, p1, p2, pi0, delta0) {
    .Call(`_AHMQ_AHM_G`, y, s, g, alpha, alpha_all, Q, G, R, N, J, K, L, p1, p2, pi0, delta0)
}

generate_sequence <- function(N) {
    .Call(`_AHMQ_generate_sequence`, N)
}

sample_int <- function(N, N1) {
    .Call(`_AHMQ_sample_int`, N, N1)
}

random_Q <- function(J, K) {
    .Call(`_AHMQ_random_Q`, J, K)
}

AHM_update <- function(Y, alpha, s, g, Q, G, pi, p1, p2, alpha_all, Q_all, N, J, K, L, N1, a_s0, a_g0, b_s0, b_g0, delta0, eta) {
    invisible(.Call(`_AHMQ_AHM_update`, Y, alpha, s, g, Q, G, pi, p1, p2, alpha_all, Q_all, N, J, K, L, N1, a_s0, a_g0, b_s0, b_g0, delta0, eta))
}

AHMQ_MCMC <- function(Y, K, s, g, pi, G, Q, alpha, N1 = 128L, chain_length = 20000L, burn_in = 10000L, a_s0 = 1.0, a_g0 = 1.0, b_s0 = 1.0, b_g0 = 1.0, p1 = 0.5, p2 = 0.5) {
    .Call(`_AHMQ_AHMQ_MCMC`, Y, K, s, g, pi, G, Q, alpha, N1, chain_length, burn_in, a_s0, a_g0, b_s0, b_g0, p1, p2)
}

dina_logL <- function(y, N, J, K, s, g, alpha, Q) {
    .Call(`_AHMQ_dina_logL`, y, N, J, K, s, g, alpha, Q)
}

dina_logL_vec <- function(y, N, J, K, chain, s, g, alpha, Q) {
    .Call(`_AHMQ_dina_logL_vec`, y, N, J, K, chain, s, g, alpha, Q)
}

bar_Dev_theta <- function(y, N, J, K, chain, s, g, alpha, Q) {
    .Call(`_AHMQ_bar_Dev_theta`, y, N, J, K, chain, s, g, alpha, Q)
}

compute_DIC <- function(y, N, J, K, chain, s, g, alpha, Q) {
    .Call(`_AHMQ_compute_DIC`, y, N, J, K, chain, s, g, alpha, Q)
}

